packages:
  - packages/*
  - themes/*

catalog:
  '@biomejs/biome': ^2.3.11
  '@clack/prompts': ^0.11.0
  '@iconify-json/carbon': ^1.2.15
  '@preact/preset-vite': ^2.10.2
  '@preact/signals': ^2.5.1
  '@tailwindcss/vite': ^4.1.18
  '@types/cross-spawn': ^6.0.6
  '@types/jquery': ^3.5.33
  '@types/node': ^25.0.3
  '@vitejs/plugin-vue': ^6.0.3
  '@vitest/ui': ^4.0.16
  bumpp: ^10.3.2
  canvas-confetti: ^1.9.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cross-spawn: ^7.0.6
  es-toolkit: ^1.43.0
  esno: ^4.8.0
  happy-dom: ^20.1.0
  lefthook: ^2.0.13
  lint-staged: ^16.2.7
  lucide: ^0.562.0
  lucide-preact: ^0.562.0
  mri: ^1.2.0
  notyf: ^3.10.0
  picocolors: ^1.1.1
  preact: ^10.28.2
  prettier: ^3.7.4
  sass: ^1.97.2
  simple-git-hooks: ^2.13.1
  stylelint: 16.23.1
  stylelint-config-standard: 39.0.0
  stylelint-order: 7.0.0
  stylelint-selector-bem-pattern: 4.0.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  taze: ^19.9.2
  terser: ^5.44.1
  tsdown: latest
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  unocss: ^66.5.12
  unplugin-vue-components: ^30.0.0
  vite: ^7.3.1
  vite-bundle-analyzer: latest
  vite-plugin-html: ^3.2.2
  vite-plugin-pwa: ^1.2.0
  vite-plugin-singlefile: ^2.3.0
  vite-plugin-svgr: ^4.5.0
  vitest: ^4.0.16
  vue: ^3.5.26
  ogl: ^1.0.11
  motion: ^12.25.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - simple-git-hooks
